<a href="https://colab.research.google.com/github/Swapnita04/Fake_News_Detection_using_Deep_Learning/blob/master/fake_news_LSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
url = 'https://raw.githubusercontent.com/Swapnita04/Fake-News-Detection/master/train.csv'
df= pd.read_csv(url)


In [ ]:
df.head()

id                                              title              author  \
0   0  House Dem Aide: We Didn’t Even See Comey’s Let...       Darrell Lucus   
1   1  FLYNN: Hillary Clinton, Big Woman on Campus - ...     Daniel J. Flynn   
2   2                  Why the Truth Might Get You Fired  Consortiumnews.com   
3   3  15 Civilians Killed In Single US Airstrike Hav...     Jessica Purkiss   
4   4  Iranian woman jailed for fictional unpublished...      Howard Portnoy   

                                                text  label  
0  House Dem Aide: We Didn’t Even See Comey’s Let...      1  
1  Ever get the feeling your life circles the rou...      0  
2  Why the Truth Might Get You Fired October 29, ...      1  
3  Videos 15 Civilians Killed In Single US Airstr...      1  
4  Print \nAn Iranian woman has been sentenced to...      1

In [ ]:
# Drop NAN values
df = df.dropna()

In [ ]:
# Get the Independant features
x = df.drop('label',axis=1)

In [ ]:
# Get the Dependant feature
y = df['label']

In [ ]:
x.shape

(18285, 4)

In [ ]:
y.shape

(18285,)

In [ ]:
import tensorflow as tf

In [ ]:
tf.__version__

'2.8.0'

In [ ]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.layers import LSTM
from tensorflow.keras.layers import Dense

In [ ]:
## Vocabulary Size
voc_size = 5000

In [ ]:
## OneHot Representation

In [ ]:
messages = x.copy()

In [ ]:
messages.reset_index(inplace = True)

In [ ]:
import nltk
import re
from nltk.corpus import stopwords

In [ ]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
# DATA PREPROCESSING
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
corpus = []
for i in range(0,len(messages)):
    print(i)
    review = re.sub('[^a-zA-Z]',' ',messages['title'][i])
    review = review.lower()
    review = review.split()
    
    review = [ps.stem(word) for word in review if word not in stopwords.words('english')]
    review = ' '.join(review)
    corpus.append(review)


Streaming output truncated to the last 5000 lines.
13285
13286
13287
13288
13289
13290
13291
13292
13293
13294
13295
13296
13297
13298
13299
13300
13301
13302
13303
13304
13305
13306
13307
13308
13309
13310
13311
13312
13313
13314
13315
13316
13317
13318
13319
13320
13321
13322
13323
13324
13325
13326
13327
13328
13329
13330
13331
13332
13333
13334
13335
13336
13337
13338
13339
13340
13341
13342
13343
13344
13345
13346
13347
13348
13349
13350
13351
13352
13353
13354
13355
13356
13357
13358
13359
13360
13361
13362
13363
13364
13365
13366
13367
13368
13369
13370
13371
13372
13373
13374
13375
13376
13377
13378
13379
13380
13381
13382
13383
13384
13385
13386
13387
13388
13389
13390
13391
13392
13393
13394
13395
13396
13397
13398
13399
13400
13401
13402
13403
13404
13405
13406
13407
13408
13409
13410
13411
13412
13413
13414
13415
13416
13417
13418
13419
13420
13421
13422
13423
13424
13425
13426
13427
13428
13429
13430
13431
13432
13433
13434
13435
13436
13437
13438
13439
13440
13441
13442
1

In [ ]:
onehot_rep = [one_hot(words,voc_size)for words in corpus] # giving index based on voc_size
onehot_rep

[[4706, 4092, 4887, 4360, 783, 4437, 4552, 688, 4, 4058],
 [1499, 3636, 4063, 4327, 1348, 3723, 1477],
 [4674, 411, 427, 700],
 [3594, 635, 4508, 4694, 2439, 661],
 [3265, 1348, 997, 1033, 3753, 4742, 1348, 3165, 2602, 3168],
 [3145,
  2864,
  2330,
  3775,
  322,
  1076,
  3941,
  1573,
  3988,
  52,
  1560,
  3124,
  2311,
  3198,
  1477],
 [3757, 4207, 3499, 3671, 3738, 4636, 2010, 3837, 1654, 2727, 1150],
 [1922, 1582, 3419, 1379, 2670, 3965, 1076, 2257, 1654, 2727, 1150],
 [3870, 1529, 4211, 2207, 906, 4024, 281, 2682, 1076, 4662],
 [1840, 4751, 3828, 3573, 3761, 3115, 1246, 4853],
 [146, 891, 1461, 4852, 590, 2737, 4157, 1529, 3823, 4416, 1818],
 [4694, 1070, 783, 4024, 1076, 2670],
 [240, 868, 1602, 4575, 3097, 360, 3275, 2612, 3842],
 [2778, 145, 3905, 3414, 4241, 3590, 1616, 1654, 2727, 1150],
 [4672, 3814, 4884, 2068, 1828, 1654, 2727, 1150],
 [3512, 928, 1491, 598, 2061, 3893, 3875, 4500, 3009, 4860],
 [2338, 4178, 3636],
 [3581, 3077, 583, 3566, 1076, 4451, 1083, 1477],
 [3

In [ ]:
## Embedding Representation

In [ ]:
sent_length = 20
embedded_docs = pad_sequences(onehot_rep, padding ='pre', maxlen = sent_length)
print(embedded_docs)

[[   0    0    0 ...  688    4 4058]
 [   0    0    0 ... 1348 3723 1477]
 [   0    0    0 ...  411  427  700]
 ...
 [   0    0    0 ... 1654 2727 1150]
 [   0    0    0 ...  591 2097 3126]
 [   0    0    0 ...  721 1720 3206]]


In [ ]:
len(embedded_docs)

18285

In [ ]:
## Creating Model

In [ ]:
#from nltk import metrics
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(LSTM(100))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])
print(model.summary)

<bound method Model.summary of <keras.engine.sequential.Sequential object at 0x7f58459d4d10>>


In [ ]:
len(embedded_docs),y.shape

(18285, (18285,))

In [ ]:
import numpy as np
x_final = np.array(embedded_docs)
y_final = np.array(y)

In [ ]:
x_final.shape,y_final.shape

((18285, 20), (18285,))

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x_final, y_final, test_size =0.33, random_state =42)

In [ ]:
# Model training

In [ ]:
model.fit(x_train,y_train,validation_data = (x_test,y_test),epochs =10, batch_size =64)

Epoch 1/10
192/192 [==============================] - 8s 32ms/step - loss: 0.3265 - accuracy: 0.8464 - val_loss: 0.1946 - val_accuracy: 0.9168
Epoch 2/10
192/192 [==============================] - 6s 29ms/step - loss: 0.1413 - accuracy: 0.9442 - val_loss: 0.2002 - val_accuracy: 0.9201
Epoch 3/10
192/192 [==============================] - 6s 29ms/step - loss: 0.1035 - accuracy: 0.9621 - val_loss: 0.2429 - val_accuracy: 0.9173
Epoch 4/10
192/192 [==============================] - 6s 30ms/step - loss: 0.0756 - accuracy: 0.9716 - val_loss: 0.2663 - val_accuracy: 0.9132
Epoch 5/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0586 - accuracy: 0.9793 - val_loss: 0.3121 - val_accuracy: 0.9133
Epoch 6/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0462 - accuracy: 0.9836 - val_loss: 0.3062 - val_accuracy: 0.9147
Epoch 7/10
192/192 [==============================] - 6s 29ms/step - loss: 0.0369 - accuracy: 0.9873 - val_loss: 0.3773 - val_accuracy: 0.9123

In [ ]:
""" ## Adding Dropout
from tensorflow.keras.layers import Dropout

## Creating Model
embedding_vector_features = 40
model = Sequential()
model.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))
model.add(Dropout(0.3))
model.add(LSTM(100))
model.add(Dropout(0.3))
model.add(Dense(1,activation='sigmoid'))
model.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])"""


"from tensorflow.keras.layers import Dropout\n\n## Creating Model\nembedding_vector_features = 40\nmodel = Sequential()\nmodel.add(Embedding(voc_size, embedding_vector_features, input_length = sent_length))\nmodel.add(Dropout(0.3))\nmodel.add(LSTM(100))\nmodel.add(Dropout(0.3))\nmodel.add(Dense(1,activation='sigmoid'))\nmodel.compile(loss='binary_crossentropy', optimizer = 'adam', metrics=['accuracy'])"

In [ ]:
# Performace metrics and Accuracy

In [ ]:
#y_pred = model.predict_classes(x_test)
y_pred = (model.predict(x_test) > 0.5).astype("int32")

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test, y_pred)

array([[3143,  276],
       [ 277, 2339]])

In [ ]:
from sklearn.metrics import accuracy_score
accuracy =(accuracy_score(y_test,y_pred))
print("ACCURACY: ", accuracy)

ACCURACY:  0.9083678541839271
